{{ if .Values.applications.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    argocd.argoproj.io/sync-wave: "-150"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # todo: remove
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: {{ .Values.applications.certManager.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-150"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # todo: remove
spec:
  isCA: true
  duration: 87600h0m0s # 10 years
  secretName: istio-ca
  commonName: istio-ca
  privateKey:
    algorithm: ECDSA
    encoding: 256
  subject:
    organizations:
      - cluster.local
      - cert-manager
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-ca
  annotations:
    argocd.argoproj.io/sync-wave: "-150"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # todo: remove
spec:
  ca:
    secretName: istio-ca
{{ end }}
