{{ if and .Values.applications.argocd.enabled (and .Values.network.enabled (and .Values.applications.istio.enabled (eq .Values.network.mode "istio"))) }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd-virtual-service
  namespace: {{ .Values.applications.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-118"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
spec:
  hosts:
    - argocd.{{ .Values.project.environment }}.{{ .Values.project.region }}.{{ .Values.project.domain }}
  gateways:
    - {{ .Values.applications.istio.gateway.namespace }}/argocd-ingress-gateway
  http:
    - route:
        - destination:
            host: argocd-server.argocd.svc.cluster.local
            port:
              number: 80
{{ end }}
