{{ if .Values.applications.argocd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: {{ .Values.applications.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.argocd.namespace }}
  project: {{ .Values.project.name }}
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: {{ .Values.applications.argocd.revision }}
    helm:
      valuesObject:
        global:
          logging:
            format: json
            level: info
        server:
          extraArgs:
            - --insecure
        applicationSet:
          service:
            portName: tcp-webhook
        configs:
          cm:
            resource.customizations: |
              cert-manager.io/Certificate:
                health.lua: |
                  hs = {}
                  if obj.status ~= nil then
                    if obj.status.conditions ~= nil then
                      for i, condition in ipairs(obj.status.conditions) do
                        if condition.type == "Ready" and condition.status == "False" then
                          hs.status = "Degraded"
                          hs.message = condition.message
                          return hs
                        end
                        if condition.type == "Ready" and condition.status == "True" then
                          hs.status = "Healthy"
                          hs.message = condition.message
                          return hs
                        end
                      end
                    end
                  end
                  hs.status = "Progressing"
                  hs.message = "Waiting for certificate"
                  return hs

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
{{ end }}
