{{ if and .Values.applications.knative.enabled (.Values.network.enabled (and .Values.applications.istio.enabled (eq .Values.network.mode "istio"))) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: {{ .Values.applications.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.applications.knative.operator.wave }}
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.knative.operator.namespace }}
  project: {{ .Values.project.name }}
  source:
    path: k12s/knative-operator/{{ .Values.project.platform }}-{{ .Values.project.environment }}-{{ .Values.project.profile }}
    kustomize:
      namespace: {{ .Values.applications.knative.operator.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{/*    syncOptions:*/}}
{{/*      - CreateNamespace=true*/}}
{{/*    managedNamespaceMetadata:*/}}  # todo
{{/*      labels:*/}}
{{/*        istio-injection: enabled*/}}
{{ end }}
