{{ if .Values.applications.loki.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: {{ .Values.applications.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.applications.loki.wave | quote }}
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.loki.namespace }}
  project: {{ .Values.project.name }}
  source:
    path: k12s/charts/loki-distributed-{{ .Values.applications.loki.revision }}/loki-distributed
    repoURL: {{ .Values.project.repository }}
    targetRevision: {{ .Values.project.branch }}
    helm:
      valuesObject:
        gateway:
          nginxConfig:
            logFormat: |
              main escape=json
                '{'
                  '"time_local":"$time_local",'
                  '"remote_addr":"$remote_addr",'
                  '"remote_user":"$remote_user",'
                  '"request":"$request",'
                  '"status": "$status",'
                  '"body_bytes_sent":"$body_bytes_sent",'
                  '"request_time":"$request_time",'
                  '"http_referrer":"$http_referer",'
                  '"http_user_agent":"$http_user_agent"'
                '}';
        loki:
          podLabels:
            app.kubernetes.io/name: loki-distributed
            app.kubernetes.io/version: v{{ .Values.applications.loki.revision }}
          config: |
            auth_enabled: false
            server:
              http_listen_port: 3100
              log_format: json
              log_level: info
            common:
              compactor_address: https://loki.loki-distributed-compactor.svc.cluster.local:3100
            distributor:
              ring:
                kvstore:
                  store: memberlist
            memberlist:
              join_members:
                - loki-distributed-memberlist
            ingester:
              chunk_block_size: 262144
              chunk_encoding: snappy
              chunk_idle_period: 30m
              chunk_retain_period: 1m
              lifecycler:
                ring:
                  kvstore:
                    store: memberlist
                  replication_factor: 1
              max_transfer_retries: 0
              wal:
                dir: /var/loki/wal
            limits_config:
              enforce_metric_name: false
              max_cache_freshness_per_query: 10m
              reject_old_samples: true
              reject_old_samples_max_age: 168h
              split_queries_by_interval: 15m
            schema_config:
              configs:
              - from: 2020-09-07
                store: boltdb-shipper
                object_store: s3
                schema: v11
                index:
                  period: 24h
                  prefix: loki_index_
            storage_config:
              aws:
                s3: s3://admin:testtesttest@minio.minio.svc.cluster.local:9000/loki-local-development
                s3forcepathstyle: true
              boltdb_shipper:
                active_index_directory: /var/loki/index
                cache_location: /var/loki/cache
                cache_ttl: 168h
                shared_store: s3
            runtime_config:
              file: /var/loki-distributed-runtime/runtime.yaml
            chunk_store_config:
              max_look_back_period: 0s
            table_manager:
              retention_deletes_enabled: false
              retention_period: 0s
            query_range:
              align_queries_with_step: true
              cache_results: true
              max_retries: 5
              results_cache:
                cache:
                  enable_fifocache: true
                  fifocache:
                    max_size_items: 1024
                    ttl: 24h
            frontend_worker:
              frontend_address: loki-distributed-query-frontend:9095
            frontend:
              compress_responses: true
              log_queries_longer_than: 5s
              tail_proxy_url: http://loki-distributed-querier:3100
            compactor:
              shared_store: s3
            ruler:
              alertmanager_url: https://alertmanager.xx
              external_url: https://alertmanager.xx
              ring:
                kvstore:
                  store: memberlist
              rule_path: /tmp/loki/scratch
              storage:
                local:
                  directory: /etc/loki/rules
                type: local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
{{ end }}
