{{ if .Values.applications.oauth2Proxy.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: {{ .Values.applications.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.applications.oauth2Proxy.wave | quote }}
  labels:
    {{- include "app-of-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.applications.oauth2Proxy.namespace }}
  project: {{ .Values.project.name }}
  source:
    path: k12s/charts/oauth2-proxy-{{ .Values.applications.oauth2Proxy.revision }}/oauth2-proxy
    repoURL: https://github.com/generic-infrastructure/terragrunt-devops
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
{{ end }}
