{{ if and .Values.applications.certManager.enabled .Values.applications.prometheus.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: {{ .Values.applications.istio.gateway.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-170"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: grafana-server-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - grafana.{{ .Values.project.environment }}.{{ .Values.project.region }}.{{ .Values.project.domain }}
  issuerRef:
    {{ if eq .Values.network.issuer "selfsigned" }}
    name: istio-ca
    kind: ClusterIssuer
    group: cert-manager.io
    {{ end }}
{{ end }}
